import "./globals.css"
import type { Metadata } from "next"
import { Inter, Open_Sans } from "next/font/google"

const inter = Inter({ subsets: ["latin"] })
const openSans = Open_Sans({
  subsets: ["latin"],
  style: "italic",
  weight: ["300", "700"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  keywords: "abobrinha, banana, maça, melão",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body>
        <h1 className={`${openSans.className} font-light`}>Next</h1>
        <main>{children}</main>
      </body>
    </html>
  )
}
